### ISSUE TITLE
Is the RaspberryPi Camera Viewer source available?

### ISSUE THREAD

**Issue by Redsandro** [pzuk/raspberry-pi-camera-viewer-embedded-example#1]
Is there any chance you'll put the _RaspberryPi Camera Viewer_ source on github?

I'm interested in running a gstreamer pipeline sec (AKA basic, vanilla) from Android.

**Comment by pzuk** [comment]
Hi Sander,

Unfortunately code is closed. Only plugins and integration codes are
available on github:
https://github.com/pzuk/raspberry-pi-camera-viewer-plugins
https://github.com/pzuk/raspberry-pi-camera-viewer-embedded-example

Thanks,
Piotr

On Sat, Aug 26, 2017 at 12:21 AM, Sander Steenhuis <notifications@github.com

**Comment by Redsandro** [comment]
Ok thank you.
